version: '3.7'

services:
  frontend:
    build:
      context: ./frontend  # Path to your React frontend Dockerfile
    networks:
      - app-network  # Connect to the app-network
    environment:
      - VITE_API_URL=http://backend:8000  # Point to backend service

  backend:
    build:
      context: ./backend  # Path to your FastAPI backend Dockerfile
    networks:
      - app-network  # Connect to the app-network
    depends_on:
      - db  # Ensure backend starts after db service

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: tosingh54  # PostgreSQL username
      POSTGRES_PASSWORD: peranofo_54  # PostgreSQL password
      POSTGRES_DB: HngDevopsDb  # PostgreSQL database name
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"  # Expose Adminer port to host
    networks:
      - app-network

  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8081:80"  # HTTP
      - "81:81"  # Admin interface
      - "443:443"  # HTTPS
      - "8090:8090"  # Custom port for access
    networks:
      - app-network
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    environment:
      DEFAULT_HOST: tosinghdevs.pakasak.com

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  data:
  letsencrypt:
